name: scheduled

on:
  workflow_dispatch:
  schedule:
    - cron: '05 6 * * *'

jobs:
  core-main:
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3' ]
        test:
          - '-s unit'
          - '-s functional -d sqlite -c 1/4'
          - '-s functional -d sqlite -c 2/4'
          - '-s functional -d sqlite -c 3/4'
          - '-s functional -d sqlite -c 4/4'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'typo3/typo3'
          ref: 'main'
          token: ${{ github.token }}
          path: 'core'

      - name: Composer install
        run: |
          core/Build/Scripts/runTests.sh -s composerInstallMax
          core/Build/Scripts/runTests.sh -s composer -- require --dev \
            phpunit/phpunit:"dev-main"

      - name: 'core/Build/Scripts/runTests.sh -p ${{ matrix.php }} ${{ matrix.test }}'
        run: |
          core/Build/Scripts/runTests.sh -p ${{ matrix.php }} ${{ matrix.test }}